name: android-arm-cpu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs: 
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: export ANDROID_NDK=$ANDROID_NDK_LATEST_HOME && ./scripts/build_android.sh
