name: android-arm-cpu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs: 
  android:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Setup Android NDK
       uses: nttld/setup-ndk@v1.4.2
       with:
          ndk-version: r21e
     - name: build
       run: |
            cd ./scripts
            export ANDROID_NDK=$ANDROID_HOME/ndk-bundle && ./build_android.sh
